version: "3.1"
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 15001:27017
    volumes:
      - ./mongo-db:/data/db
      - ./init-db:/docker-entrypoint-initdb.d
# docker-compose up -d
# docker-compose up
# docker-compose down
